import enum
import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum,
    ForeignKey,
    Integer,
    String,
    UniqueConstraint,
    Uuid,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class UserStatus(str, enum.Enum):
    active = "active"
    banned = "banned"


class AuthProvider(str, enum.Enum):
    telegram = "telegram"
    phone = "phone"
    email = "email"
    # An anonymous account the Android app created on first launch. The
    # provider_uid is generated by the head, never by the client: a
    # client-chosen identifier is a client-guessable one, and guessing it
    # would hand over someone else's account.
    device = "device"


class ClientType(str, enum.Enum):
    bot = "bot"
    android = "android"


class User(Base):
    """The one and only identity. Telegram/phone/email are just ways in — see AuthIdentity."""

    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    status: Mapped[UserStatus] = mapped_column(Enum(UserStatus, name="user_status"), default=UserStatus.active)

    # When the time bought with the last rewarded ad runs out. Null means
    # never bought any. This is the entire entitlement model: access is not
    # a status somebody holds, it is a stretch of time paid for with
    # attention (app/services/access.py).
    access_expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    # True when the current stretch came from the fallback rather than from
    # a watched ad, which puts the user on the lower-priority class.
    access_is_grace: Mapped[bool] = mapped_column(Boolean, default=False)
    # Rate-limits the fallback: "the ad failed" is a claim the client makes
    # about itself, and without a limit it is the cheapest way never to see
    # one.
    grace_granted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    auth_identities: Mapped[list["AuthIdentity"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    sessions: Mapped[list["UserSession"]] = relationship(back_populates="user", cascade="all, delete-orphan")


class AuthIdentity(Base):
    """One row per way a user can log in. A user can hold several (telegram + phone, etc.)."""

    __tablename__ = "auth_identities"
    __table_args__ = (UniqueConstraint("provider", "provider_uid", name="uq_auth_identity_provider_uid"),)

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(Uuid, ForeignKey("users.id", ondelete="CASCADE"))
    provider: Mapped[AuthProvider] = mapped_column(Enum(AuthProvider, name="auth_provider"))
    provider_uid: Mapped[str] = mapped_column(String(255))
    verified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    user: Mapped["User"] = relationship(back_populates="auth_identities")


class UserSession(Base):
    """An issued client session/token. Counted against plans.max_devices.

    This is what authenticates the Android app. The bot does not need one —
    it runs on our own server and carries the service token, which
    authenticates the *caller*; a token shipped inside an APK would
    authenticate nobody, because anyone who unzips the APK has it.

    Only the hash of the token is stored. A stolen database backup then
    yields no working tokens, which is the same reason passwords are hashed
    — except the reasoning about *which* hash differs: see `token_hash`.
    """

    __tablename__ = "sessions"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(Uuid, ForeignKey("users.id", ondelete="CASCADE"))
    client_type: Mapped[ClientType] = mapped_column(Enum(ClientType, name="client_type"))
    issued_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # SHA-256 of the bearer token. Deliberately *not* scrypt: the token is 32
    # random bytes we generated, not a human-chosen password, so there is no
    # dictionary to slow an attacker down against — and this hash is computed
    # on every single authenticated request, where scrypt's memory-hardness
    # would be a self-inflicted denial of service.
    token_hash: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    # Rough "is this install still alive" signal, updated at most hourly so a
    # chatty client cannot turn every request into a write.
    last_seen_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    # Free-form, for the admin panel: "Android 14 / Pixel 7". Never used for
    # authentication — it is whatever the client claimed.
    device_label: Mapped[str | None] = mapped_column(String(120), nullable=True)

    user: Mapped["User"] = relationship(back_populates="sessions")


class LinkCode(Base):
    """A short code that attaches an anonymous app account to a Telegram one.

    Exists because the Android app registers anonymously: the account is real
    but has no way back if the phone is lost. The app shows a code, the user
    sends it to the bot, and the two accounts become one.

    Short and short-lived on purpose — it is typed by a human into a chat.
    Six digits would be trivially brute-forceable if it lived for a day, so
    it expires in minutes and is single-use, and attempts are capped.
    """

    __tablename__ = "link_codes"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(Uuid, ForeignKey("users.id", ondelete="CASCADE"))
    code: Mapped[str] = mapped_column(String(12), unique=True, index=True)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    redeemed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class AdNonce(Base):
    """A token covering one run through an access package's ads.

    Without it, a single recorded HTTP call would be an unlimited access
    generator: replay "I watched an ad" forever and never watch one. The
    token has to be issued by the head moments before, is spent on
    redemption and expires quickly.

    This is friction rather than security — a modified client can still
    request a token and claim the reward without showing anything. The real
    control is the ad network's server-to-server callback; see
    `access.redeem_verified` and the `AD_SSV_REQUIRED` setting.
    """

    __tablename__ = "ad_nonces"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(Uuid, ForeignKey("users.id", ondelete="CASCADE"))
    nonce: Mapped[str] = mapped_column(String(64), unique=True, index=True)
    # Which package this run is for. Stored server-side because the server
    # decides what a view is worth — a client that could name its own
    # reward would name a large one.
    package: Mapped[str] = mapped_column(String(16), default="hour")
    views_required: Mapped[int] = mapped_column(Integer, default=1)
    views_done: Mapped[int] = mapped_column(Integer, default=0)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    redeemed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
